# Solicitações de refúgio no Brasil
##### Elaborado por Bruna Lopes, Paula Duque, Rogério Silva e Yasmini Gomes

## Contextualização

Com a Convenção de 1951, imigrantes que buscavam por proteção ou melhores condições de vida em outro país foram entitulados refugiados e foi estipulado o princípio denominado non-refoulement, que estabelece a não obrigatoriedade de
retorno ao país de origem. Dentre os fatores que desencadeiam esse processo, destacamos: condição de vida miserável, perseguição política, discriminação racial e existência de conflitos armados.

De acordo com o Comitê Nacional para Refugiados (Conare), a quantidade de pessoas que pedem refúgio no Brasil vem aumentando a cada ano. Isso ocorre em função da permissividade das leis nacionais, quando comparadas aos países da Europa e dos
Estados Unidos, que são restritivos quanto à legalidade dos imigrantes e acesso aos recursos. A legislação brasileira, redigida em parceria com o Alto Comissariado das Nações Unidas para Refugiados (Acnur), é considerada pela ONU como uma das
mais modernas e abrangentes do mundo.

A responsabilidade do país em receber refugiados abrange diversas esferas, dentre as quais podemos citar: Direitos Humanos, Polícia Federal, Ministério das Relações Exteriores, Ministério da Saúde, Trabalho e Educação. Cada uma dessas desempenha
um papel para auxiliar na integração entre os refugiados e a população local, ao passo que seja garantam o cumprimento dos direitos universais, integração no mercado de trabalho e apoio psíquico, dentre outras questões.

## Objetivo

Diante do aumento na quantidade de refugiados no Brasil, o objetivo desse projeto é elaborar um dashboard que auxilie a área de estratégia do Governo no acompanhamento das solicitações de refúgio, bem como no mapeamento de quais localidades possuem um maior número de solicitações e se apresentam uma infraestrutura adequada para suportar essa demanda. A partir disso, poderão ser identificadas regiões críticas e criadas novas políticas públicas.

## Etapas

1. **Escolha do problema:** Análise das solicitações de refúgio no Brasil para tomada de decisão
2. **Coleta de dados:** Repositório de dados públicos disponibilizados pelo Governo
3. **Processamento:** Preparação dos dados sobre pedidos de refúgio com Python
4. **Exploração dos dados:** Limpeza dos dados e construção de novos parâmetros utilizando bases auxiliares com Python
5. **Visualização dos resultados:** Elaboração de um painel no Power BI
6. **Análise crítica:** Análise geral dos dados para responder as hipóteses e questões do projeto

## Hipóteses e questões

- Quantas solicitações de refúgio o Brasil recebe por ano?
- Quantas nacionalidades enxergam o Brasil como refúgio?
- Quais foram os principais eventos que causaram impacto no crescimento de refugiados no Brasil?
- Quais estados brasileiros mais recebem refugiados?
- Quais estados possuem programas de acolhimento?
- Quanto tempo, em média, demora para que uma solicitação de refúgio seja julgada?

In [326]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [327]:
pip install pyxlsb

Requirement already satisfied: pyxlsb in c:\users\roger\anaconda3\lib\site-packages (1.0.9)
Note: you may need to restart the kernel to use updated packages.

In [380]:
sheets = ['2021', '2020', '2019', '2018', '2017', '2016', '2015']
colunas = ['STATUS', 'PAÍS DE ORIGEM', 'DATA SOLICITAÇÃO', 'ANO DE NASCIMENTO', 'CIDADE SOLICITAÇÃO', 'DATA DA  DECISÃO']

In [381]:
df = pd.read_excel("data-solicitacoes-refugio-brasil/decisoes-pedidos-refugio.xlsb", engine='pyxlsb',
                  sheet_name= sheets, usecols= colunas)

In [382]:
df['2021']

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO
0,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,2004,RIO DE JANEIRO,44232
1,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,1991,PORTO ALEGRE,44232
2,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,1999,SÃO PAULO,44232
3,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,2003,RIO DE JANEIRO,44232
4,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,1993,SÃO PAULO,44232
...,...,...,...,...,...,...
2095,CESSAÇÃO,2015,SÍRIA,1968,SÃO PAULO,44364
2096,CESSAÇÃO,2014,IRAQUE,1986,RIO DE JANEIRO,44364
2097,CESSAÇÃO,2013,LÍBANO,1988,SÃO PAULO,44364
2098,CESSAÇÃO,2014,SÍRIA,1990,GUARUJÁ,44364
2099,CESSAÇÃO,2013,SUDÃO,1987,BRASÍLIA,44364

In [383]:
df['2015']

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO
0,ELEGIBILIDADE / DEFERIMENTO,2014,AFEGANISTÃO,1992,BRASÍLIA,42118.0
1,ELEGIBILIDADE / DEFERIMENTO,2014,AFEGANISTÃO,1986,RIO DE JANEIRO,42118.0
2,ELEGIBILIDADE / DEFERIMENTO,2014,AFEGANISTÃO,1989,RIO DE JANEIRO,42118.0
3,ELEGIBILIDADE / DEFERIMENTO,2014,AFEGANISTÃO,2011,RIO DE JANEIRO,42118.0
4,ELEGIBILIDADE / DEFERIMENTO,2014,AFEGANISTÃO,2012,RIO DE JANEIRO,42118.0
...,...,...,...,...,...,...
1757,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SÃO PAULO,42349.0
1758,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SÃO PAULO,42349.0
1759,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SÃO PAULO,42349.0
1760,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASÍLIA,42349.0
1761,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SÃO PAULO,42349.0

In [384]:
solicitacoes = pd.concat(df, ignore_index=True)

In [385]:
solicitacoes['DATA DA  DECISÃO'] = pd.to_datetime(solicitacoes['DATA DA  DECISÃO'], unit='D', origin='1899-12-30')

In [386]:
solicitacoes.dropna(inplace=True)

In [387]:
solicitacoes['PAÍS DE ORIGEM'] = solicitacoes['PAÍS DE ORIGEM'].str.strip()
solicitacoes['CIDADE SOLICITAÇÃO'] = solicitacoes['CIDADE SOLICITAÇÃO'].str.strip()

In [388]:
solicitacoes['PAÍS DE ORIGEM'] = solicitacoes['PAÍS DE ORIGEM'].str.upper()
solicitacoes['CIDADE SOLICITAÇÃO'] = solicitacoes['CIDADE SOLICITAÇÃO'].str.upper()

In [389]:
solicitacoes

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO
0,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,2004,RIO DE JANEIRO,2021-02-05
1,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,1991,PORTO ALEGRE,2021-02-05
2,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,1999,SÃO PAULO,2021-02-05
3,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,2003,RIO DE JANEIRO,2021-02-05
4,ELEGIBILIDADE - DEFERIDO,2020,SÍRIA,1993,SÃO PAULO,2021-02-05
...,...,...,...,...,...,...
74920,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SÃO PAULO,2015-12-11
74921,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SÃO PAULO,2015-12-11
74922,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SÃO PAULO,2015-12-11
74923,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASÍLIA,2015-12-11
74924,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SÃO PAULO,2015-12-11

In [390]:
import unidecode

def retirar_acento(expression):
    try:
        return unidecode.unidecode(expression)
    except:
        return 'INDEFINIDO'

#solicitacoes['PAÍS DE ORIGEM'] = solicitacoes['PAÍS DE ORIGEM'].apply(retirar_acento)
#solicitacoes['CIDADE SOLICITAÇÃO'] = solicitacoes['CIDADE SOLICITAÇÃO'].apply(retirar_acento)

In [391]:
solicitacoes['PAÍS DE ORIGEM'] = solicitacoes['PAÍS DE ORIGEM'].apply(retirar_acento)

In [392]:
solicitacoes['CIDADE SOLICITAÇÃO'] = solicitacoes['CIDADE SOLICITAÇÃO'].apply(retirar_acento)

In [393]:
solicitacoes['CIDADE SOLICITAÇÃO'].sort_values().unique()

array(['"A DEFINIR"', '0X2A', 'ALTAMIRA', 'ANANINDEUA', 'ANAPOLIS',
       'ANGRA DOS REIS', 'ARACAJU', 'ARACATUBA', 'ARAGUAINA',
       'ARARAQUARA', 'BAGE', 'BARRA DO GARCA', 'BARRACAO', 'BAURU',
       'BELEM', 'BELO HORIZONTE', 'BOA VISTA', 'BRAS', 'BRASILEIA',
       'BRASILIA', 'CABEDELO', 'CACERES', 'CAMPINA GRANDE', 'CAMPINAS',
       'CAMPO DOS GOYTACAZES', 'CAMPO GRANDE', 'CARUARU', 'CASCAVEL',
       'CAXIAS DO SUL', 'CHAPECO', 'CORUMBA', 'CRICIUMA', 'CRUZEIRO',
       'CRUZEIRO DO SUL', 'CUIABA', 'CURITIBA', 'DIONISIO CERQUEIRA',
       'DIVINOPOLIS', 'DIVIN[OPOLIS', 'DOIS VIZINHOS', 'DOURADOS',
       'EPITACIOLANDIA', 'ERECHIM', 'FLORIANOPOLIS', 'FORTALEZA',
       'FOZ DO IGUACU', 'GOIANIA', 'GOVERNADOR VALADARES', 'GUAIRA',
       'GUAJARA', 'GUARAPUAVA', 'GUARUJA', 'GUARULHOS', 'ILHEUS',
       'IMPERATRIZ', 'ITAI', 'ITAJAI', 'ITU', 'JAGUARAO', 'JALES',
       'JATAI', 'JI-PARANA', 'JOAO PESSOA', 'JOINVILLE', 'JUAZEIRO',
       'JUIZ DE FORA', 'LAGES', 'LONDRINA', 'MACAE', 'MACAPA', 'MACEIO',
       'MANAUS', 'MARABA', 'MARINGA', 'MINEIROS', 'NATAL', 'NAVIRAI',
       'NITEROI', 'NOVA IGUACU', 'OIAPOQUE', 'PACARAIMA', 'PALMAS',
       'PARANAGUA', 'PARNAIBA', 'PASSO FUNDO', 'PELOTAS', 'PIRACICABA',
       'PIRENOPOLIS', 'PONTA GROSSA', 'PONTA PORA', 'PORTO ALEGRE',
       'PORTO GRANDE', 'PORTO SEGURO', 'PORTO VELHO',
       'PRESIDENTE PRUDENTE', 'RECIFE', 'REDENCAO', 'RIBEIRAO PRETO',
       'RIO BRANCO', 'RIO DE JANEIRO', 'RIO GRANDE', 'RONDONOPOLIS',
       'SALGUEIRO', 'SALVADOR', 'SANTA CRUZ DO SUL', 'SANTA MARIA',
       'SANTANA DO LIVRAMENTO', 'SANTAREM', 'SANTO ANGELO', 'SANTOS',
       'SAO JOSE DO RIO PRETO', 'SAO JOSE DOS CAMPOS', 'SAO LUIS',
       'SAO MATEUS', 'SAO PAULO', 'SAO SEBASTIAO', 'SINOP', 'SOROCABA',
       'TABATINGA', 'TERESINA', 'TRES LAGOAS', 'UBERABA', 'UBERLANDIA',
       'URUGUAIANA', 'VARGINHA', 'VILHENA', 'VITORIA',
       'VITORIA DA CONQUISTA', 'VITORIA DO PALMAR', 'VOLTA REDONDA'],
      dtype=object)

In [394]:
padrao_nome = {'AFRICA DO SUL': ['AFRICA'],
               'CABO VERDE': ['CABO-VERDE'],
               'CONGO-BRAZZAVILLE': ['REP.DO CONGO', 'CONGO'],
               'ESTADOS UNIDOS': ['ESTADOS UNIDOS DA AMERICA'],
               'GUINE': ['GUINE-CONACRI', 'REP. DA GUINE'],
               'GUINE BISSAU': ['GUINE-BISSAU', 'REP. DA GUINE-BISSAU'],
               'IEMEN': ['IEMEN '],
               'JORDANIA': ['JORDANIA/PALESTINA'],
               'REP. DEM DO CONGO': ['REPUBLICA DEMOCRATICA DO CONGO', 'REP.DEM DO CONGO', 'REP. DEM. DO CONGO', 'RDC'],
               'REP. DOMINICANA': ['REPUBLICA DOMINICANA', 'REP.DOMINICANA'],
               'REP. TCHECA': ['REPUBLICA TCHECA'],
               'SIRIA': ['PALESTINA/SIRIA'],
               'SRI-LANKA': ['SRI LANKA'],
               'RUSSIA': ['UNIAO SOVIETICA']
              }

In [395]:
def ajustar_pais(pais):
    for chave, valor in padrao_nome.items():
        #print(valor)
        if pais in valor:
            return chave
        else:
            pais_mantido = pais
    return pais_mantido

solicitacoes['PAÍS DE ORIGEM'] = solicitacoes['PAÍS DE ORIGEM'].apply(ajustar_pais)

In [396]:
padrao_nome = {'DIVINOPOLIS': ['DIVIN[OPOLIS'],
               'CAMPOS DOS GOYTACAZES': ['CAMPO DOS GOYTACAZES'],
               'SANTA VITORIA DO PALMAR': ['VITORIA DO PALMAR'],
               'SAO PAULO': ['BRAS'],
               'BARRA DO GARCAS': ['BARRA DO GARCA']
              }

solicitacoes['CIDADE SOLICITAÇÃO'] = solicitacoes['CIDADE SOLICITAÇÃO'].apply(ajustar_pais)

In [397]:
solicitacoes

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO
0,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2004,RIO DE JANEIRO,2021-02-05
1,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1991,PORTO ALEGRE,2021-02-05
2,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1999,SAO PAULO,2021-02-05
3,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2003,RIO DE JANEIRO,2021-02-05
4,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1993,SAO PAULO,2021-02-05
...,...,...,...,...,...,...
74920,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SAO PAULO,2015-12-11
74921,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SAO PAULO,2015-12-11
74922,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SAO PAULO,2015-12-11
74923,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASILIA,2015-12-11
74924,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SAO PAULO,2015-12-11

In [398]:
solicitacoes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74710 entries, 0 to 74924
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   STATUS              74710 non-null  object
 1   DATA SOLICITAÇÃO    74710 non-null  int64
 2   PAÍS DE ORIGEM      74710 non-null  object
 3   ANO DE NASCIMENTO   74710 non-null  object
 4   CIDADE SOLICITAÇÃO  74710 non-null  object
 5   DATA DA  DECISÃO    74710 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 4.0+ MB

In [399]:
solicitacoes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74710 entries, 0 to 74924
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   STATUS              74710 non-null  object
 1   DATA SOLICITAÇÃO    74710 non-null  int64
 2   PAÍS DE ORIGEM      74710 non-null  object
 3   ANO DE NASCIMENTO   74710 non-null  object
 4   CIDADE SOLICITAÇÃO  74710 non-null  object
 5   DATA DA  DECISÃO    74710 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 4.0+ MB

In [400]:
paises = pd.read_excel('data-solicitacoes-refugio-brasil/lista-paises-continentes.xlsx', usecols= ['País', 'Continente'])

In [401]:
paises['País'] = paises['País'].str.strip()
paises['País'] = paises['País'].apply(retirar_acento)

In [402]:
paises

              País Continente
0      AFEGANISTAO       ÁSIA
1    AFRICA DO SUL     ÁFRICA
2          ALBANIA     EUROPA
3         ALEMANHA     EUROPA
4          ANDORRA     EUROPA
..             ...        ...
195       VATICANO     EUROPA
196      VENEZUELA    AMÉRICA
197         VIETNA       ÁSIA
198         ZAMBIA     ÁFRICA
199       ZIMBABUE     ÁFRICA

[200 rows x 2 columns]

In [403]:
df_solicitacoes = pd.merge(left= solicitacoes, right= paises, 
                           left_on= 'PAÍS DE ORIGEM', right_on= 'País', 
                           how= 'left').drop(columns = ['País'])

In [404]:
df_solicitacoes

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO,Continente
0,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2004,RIO DE JANEIRO,2021-02-05,ÁSIA
1,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1991,PORTO ALEGRE,2021-02-05,ÁSIA
2,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1999,SAO PAULO,2021-02-05,ÁSIA
3,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2003,RIO DE JANEIRO,2021-02-05,ÁSIA
4,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1993,SAO PAULO,2021-02-05,ÁSIA
...,...,...,...,...,...,...,...
74705,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SAO PAULO,2015-12-11,ÁFRICA
74706,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SAO PAULO,2015-12-11,ÁFRICA
74707,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SAO PAULO,2015-12-11,ÁFRICA
74708,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASILIA,2015-12-11,AMÉRICA
74709,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SAO PAULO,2015-12-11,ÁFRICA

In [405]:
df_solicitacoes[df_solicitacoes['Continente'].isnull()]['PAÍS DE ORIGEM'].unique()

array(['MODOU NIANG', 'NAO INFORMADO', 'APATRIDA'], dtype=object)

In [406]:
df_solicitacoes = df_solicitacoes[~(df_solicitacoes['Continente'].isnull())]

In [407]:
df_solicitacoes

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO,Continente
0,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2004,RIO DE JANEIRO,2021-02-05,ÁSIA
1,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1991,PORTO ALEGRE,2021-02-05,ÁSIA
2,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1999,SAO PAULO,2021-02-05,ÁSIA
3,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2003,RIO DE JANEIRO,2021-02-05,ÁSIA
4,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1993,SAO PAULO,2021-02-05,ÁSIA
...,...,...,...,...,...,...,...
74705,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SAO PAULO,2015-12-11,ÁFRICA
74706,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SAO PAULO,2015-12-11,ÁFRICA
74707,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SAO PAULO,2015-12-11,ÁFRICA
74708,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASILIA,2015-12-11,AMÉRICA
74709,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SAO PAULO,2015-12-11,ÁFRICA

Fonte: http://blog.mds.gov.br/redesuas/lista-de-municipios-brasileiros/

In [408]:
cidadesBR = pd.read_excel("data-solicitacoes-refugio-brasil/Lista-de-Municípios-com-IBGE-Brasil.xlsx", 
                          sheet_name= 'Lista de Municípios IBGE',
                          usecols= ['UF', 'Região', 'Município', 'Capital', 'População 2010'])

In [409]:
cidadesBR

      UF              Município               Região  População 2010  Capital
0     RO  Alta Floresta D´oeste         Região Norte         24392.0      NaN
1     RO              Ariquemes         Região Norte         90353.0      NaN
2     RO                 Cabixi         Região Norte          6313.0      NaN
3     RO                 Cacoal         Região Norte         78574.0      NaN
4     RO             Cerejeiras         Região Norte         17029.0      NaN
...   ..                    ...                  ...             ...      ...
5565  GO             Vianópolis  Região Centro-Oeste         12548.0      NaN
5566  GO         Vicentinópolis  Região Centro-Oeste          7371.0      NaN
5567  GO               Vila Boa  Região Centro-Oeste          4735.0      NaN
5568  GO          Vila Propício  Região Centro-Oeste          5145.0      NaN
5569  DF               Brasília  Região Centro-Oeste       2570160.0  Capital

[5570 rows x 5 columns]

In [410]:
cidadesBR['Capital'] = cidadesBR['Capital'].apply(lambda municipio:'SIM' if municipio == 'Capital' else 'NÃO')

In [411]:
cidadesBR

      UF              Município               Região  População 2010 Capital
0     RO  Alta Floresta D´oeste         Região Norte         24392.0     NÃO
1     RO              Ariquemes         Região Norte         90353.0     NÃO
2     RO                 Cabixi         Região Norte          6313.0     NÃO
3     RO                 Cacoal         Região Norte         78574.0     NÃO
4     RO             Cerejeiras         Região Norte         17029.0     NÃO
...   ..                    ...                  ...             ...     ...
5565  GO             Vianópolis  Região Centro-Oeste         12548.0     NÃO
5566  GO         Vicentinópolis  Região Centro-Oeste          7371.0     NÃO
5567  GO               Vila Boa  Região Centro-Oeste          4735.0     NÃO
5568  GO          Vila Propício  Região Centro-Oeste          5145.0     NÃO
5569  DF               Brasília  Região Centro-Oeste       2570160.0     SIM

[5570 rows x 5 columns]

In [412]:
cidadesBR['Região'] = cidadesBR['Região'].str.upper()
cidadesBR['Município'] = cidadesBR['Município'].str.upper()
cidadesBR['Município'] = cidadesBR['Município'].apply(retirar_acento)

In [413]:
cidadesBR

      UF              Município               Região  População 2010 Capital
0     RO  ALTA FLORESTA D'OESTE         REGIÃO NORTE         24392.0     NÃO
1     RO              ARIQUEMES         REGIÃO NORTE         90353.0     NÃO
2     RO                 CABIXI         REGIÃO NORTE          6313.0     NÃO
3     RO                 CACOAL         REGIÃO NORTE         78574.0     NÃO
4     RO             CEREJEIRAS         REGIÃO NORTE         17029.0     NÃO
...   ..                    ...                  ...             ...     ...
5565  GO             VIANOPOLIS  REGIÃO CENTRO-OESTE         12548.0     NÃO
5566  GO         VICENTINOPOLIS  REGIÃO CENTRO-OESTE          7371.0     NÃO
5567  GO               VILA BOA  REGIÃO CENTRO-OESTE          4735.0     NÃO
5568  GO          VILA PROPICIO  REGIÃO CENTRO-OESTE          5145.0     NÃO
5569  DF               BRASILIA  REGIÃO CENTRO-OESTE       2570160.0     SIM

[5570 rows x 5 columns]

In [414]:
df_solicitacoes2 = pd.merge(left= df_solicitacoes, right= cidadesBR, 
                           left_on= 'CIDADE SOLICITAÇÃO', right_on= 'Município', 
                           how= 'left', indicator= False).drop(columns = ['Município'])

In [415]:
df_solicitacoes2

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO,Continente,UF,Região,População 2010,Capital
0,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2004,RIO DE JANEIRO,2021-02-05,ÁSIA,RJ,REGIÃO SUDESTE,6320446.0,SIM
1,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1991,PORTO ALEGRE,2021-02-05,ÁSIA,RS,REGIÃO SUL,1409351.0,SIM
2,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1999,SAO PAULO,2021-02-05,ÁSIA,SP,REGIÃO SUDESTE,11253503.0,SIM
3,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2003,RIO DE JANEIRO,2021-02-05,ÁSIA,RJ,REGIÃO SUDESTE,6320446.0,SIM
4,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1993,SAO PAULO,2021-02-05,ÁSIA,SP,REGIÃO SUDESTE,11253503.0,SIM
...,...,...,...,...,...,...,...,...,...,...,...
104969,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SAO PAULO,2015-12-11,ÁFRICA,SP,REGIÃO SUDESTE,11253503.0,SIM
104970,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SAO PAULO,2015-12-11,ÁFRICA,SP,REGIÃO SUDESTE,11253503.0,SIM
104971,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SAO PAULO,2015-12-11,ÁFRICA,SP,REGIÃO SUDESTE,11253503.0,SIM
104972,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASILIA,2015-12-11,AMÉRICA,DF,REGIÃO CENTRO-OESTE,2570160.0,SIM
104973,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SAO PAULO,2015-12-11,ÁFRICA,SP,REGIÃO SUDESTE,11253503.0,SIM

In [416]:
muni = df_solicitacoes2[~(df_solicitacoes2['Capital'].isnull())]['CIDADE SOLICITAÇÃO'].unique()

In [417]:
padrao_nome = {'DIVINOPOLIS': ['DIVIN[OPOLIS'],
               'CAMPOS DOS GOYTACAZES': ['CAMPO DOS GOYTACAZES'],
               'SANTA VITORIA DO PALMAR': ['VITORIA DO PALMAR'],
               'SAO PAULO': ['BRAS'],
               'BARRA DO GARCAS': ['BARRA DO GARCA']
              }

In [418]:
muni

array(['RIO DE JANEIRO', 'PORTO ALEGRE', 'SAO PAULO', 'PIRACICABA',
       'BRASILIA', 'SOROCABA', 'MANAUS', 'NITEROI', 'RECIFE',
       'CAXIAS DO SUL', 'CURITIBA', 'ITAJAI', 'BOA VISTA',
       'SAO JOSE DOS CAMPOS', 'MACEIO', 'ANGRA DOS REIS', 'GUARULHOS',
       'VARGINHA', 'BARRACAO', 'FORTALEZA', 'CAMPINAS', 'RIO BRANCO',
       'BAURU', 'SAO LUIS', 'CRICIUMA', 'PONTA GROSSA', 'PORTO VELHO',
       'JATAI', 'VITORIA', 'FOZ DO IGUACU', 'PACARAIMA', 'FLORIANOPOLIS',
       'GUARAPUAVA', 'ARACAJU', 'PONTA PORA', 'UBERLANDIA', 'JOAO PESSOA',
       'DIVINOPOLIS', 'NOVA IGUACU', 'CUIABA', 'ARARAQUARA', 'SANTAREM',
       'SINOP', 'BELO HORIZONTE', 'TABATINGA', 'URUGUAIANA',
       'SANTA MARIA', 'REDENCAO', 'ILHEUS', 'GOIANIA', 'IMPERATRIZ',
       'LONDRINA', 'SAO JOSE DO RIO PRETO', 'VOLTA REDONDA', 'BRASILEIA',
       'MARINGA', 'JAGUARAO', 'VILHENA', 'PORTO GRANDE',
       'CAMPOS DOS GOYTACAZES', 'GUAIRA', 'SALVADOR', 'CAMPO GRANDE',
       'NATAL', 'RONDONOPOLIS', 'SANTA VITORIA DO PALMAR', 'BAGE',
       'JOINVILLE', 'GUARUJA', 'TERESINA', 'ITU', 'JI-PARANA', 'CHAPECO',
       'CASCAVEL', 'DOURADOS', 'GUAJARA', 'RIBEIRAO PRETO', 'ARACATUBA',
       'BELEM', 'ANAPOLIS', 'MINEIROS', 'PRESIDENTE PRUDENTE', 'MACAE',
       'JUIZ DE FORA', 'JUAZEIRO', 'ERECHIM', 'GOVERNADOR VALADARES',
       'LAGES', 'CRUZEIRO', 'ALTAMIRA', 'MARABA', 'SANTA CRUZ DO SUL',
       'MACAPA', 'EPITACIOLANDIA', 'DIONISIO CERQUEIRA', 'CORUMBA',
       'PORTO SEGURO', 'TRES LAGOAS', 'OIAPOQUE', 'ARAGUAINA', 'UBERABA',
       'CAMPINA GRANDE', 'ANANINDEUA', 'DOIS VIZINHOS', 'NAVIRAI',
       'CACERES', 'PALMAS', 'JALES', 'SANTOS', 'PIRENOPOLIS',
       'PASSO FUNDO', 'SANTO ANGELO', 'CABEDELO', 'CARUARU',
       'SAO SEBASTIAO', 'CRUZEIRO DO SUL', 'VITORIA DA CONQUISTA',
       'PELOTAS', 'SALGUEIRO', 'SAO MATEUS', 'ITAI', 'PARNAIBA',
       'RIO GRANDE', 'BARRA DO GARCAS', 'SANTANA DO LIVRAMENTO',
       'PARANAGUA'], dtype=object)

In [419]:
def cont(x, coluna):
    for y in x:
        w = cidadesBR[cidadesBR['Município'] == y]
        if w['Município'].count() > 1:
            z = w[w['População 2010'] == w['População 2010'].max()][coluna]
            return z
        else: 
            z = w[coluna]
            return z

In [420]:
cont(['BOA VISTA'], 'Região')

138    REGIÃO NORTE
Name: Região, dtype: object

In [421]:
def teste(x1):
    x2 = cidadesBR[cidadesBR['Município'] == x1]
    x3 = x2['Município'].count()
    #print(x3)
    #return x1
    if x3 > 1:
        x4 = x2.loc[x2['População 2010'].idxmax()]['UF']
        return x4
    else:
        x4 = x2['UF']
        return x4

In [422]:
tt('CASCAVEL')

'PR'

In [423]:
def tt(y):
    try:
        w = cidadesBR[cidadesBR['Município'] == y]
        x = w.loc[w['População 2010'].idxmax()]['UF']
        return x
    except:
        return y

In [424]:
df_solicitacoes2[df_solicitacoes2['CIDADE SOLICITAÇÃO'] == 'BARRACAO']

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO,Continente,UF,Região,População 2010,Capital
34,ELEGIBILIDADE - DEFERIDO,2017,CUBA,1977,BARRACAO,2021-02-05,AMÉRICA,PR,REGIÃO SUL,9735.0,NÃO
35,ELEGIBILIDADE - DEFERIDO,2017,CUBA,1977,BARRACAO,2021-02-05,AMÉRICA,RS,REGIÃO SUL,5357.0,NÃO
2211,ELEGIBILIDADE - INDEFERIDO,2015,BANGLADESH,1972,BARRACAO,2021-06-17,ÁSIA,PR,REGIÃO SUL,9735.0,NÃO
2212,ELEGIBILIDADE - INDEFERIDO,2015,BANGLADESH,1972,BARRACAO,2021-06-17,ÁSIA,RS,REGIÃO SUL,5357.0,NÃO
8057,ELEGIBILIDADE - DEFERIDO,2019,VENEZUELA,1974,BARRACAO,2020-01-31,AMÉRICA,PR,REGIÃO SUL,9735.0,NÃO
...,...,...,...,...,...,...,...,...,...,...,...
104614,ELEGIBILIDADE / INDEFERIMENTO,2014,GUINE BISSAU,1977,BARRACAO,2015-10-22,ÁFRICA,RS,REGIÃO SUL,5357.0,NÃO
104672,ELEGIBILIDADE / INDEFERIMENTO,2014,NIGER,1980,BARRACAO,2015-10-22,ÁFRICA,PR,REGIÃO SUL,9735.0,NÃO
104673,ELEGIBILIDADE / INDEFERIMENTO,2014,NIGER,1980,BARRACAO,2015-10-22,ÁFRICA,RS,REGIÃO SUL,5357.0,NÃO
104909,PERDA / RENÚNCIA,2012,SIRIA,1988,BARRACAO,2015-12-11,ÁSIA,PR,REGIÃO SUL,9735.0,NÃO
104910,PERDA / RENÚNCIA,2012,SIRIA,1988,BARRACAO,2015-12-11,ÁSIA,RS,REGIÃO SUL,5357.0,NÃO

In [425]:
cidadesBR[cidadesBR['Município'] == 'CASCAVEL']['Município'].value_counts().item()

2

In [426]:
df_solicitacoes['teste'] = df_solicitacoes['CIDADE SOLICITAÇÃO'].apply(lambda row: tt(row))

C:\Users\roger\AppData\Local\Temp/ipykernel_9896/3870171710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_solicitacoes['teste'] = df_solicitacoes['CIDADE SOLICITAÇÃO'].apply(lambda row: tt(row))

In [427]:
df_solicitacoes

,STATUS,DATA SOLICITAÇÃO,PAÍS DE ORIGEM,ANO DE NASCIMENTO,CIDADE SOLICITAÇÃO,DATA DA DECISÃO,Continente,teste
0,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2004,RIO DE JANEIRO,2021-02-05,ÁSIA,RJ
1,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1991,PORTO ALEGRE,2021-02-05,ÁSIA,RS
2,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1999,SAO PAULO,2021-02-05,ÁSIA,SP
3,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,2003,RIO DE JANEIRO,2021-02-05,ÁSIA,RJ
4,ELEGIBILIDADE - DEFERIDO,2020,SIRIA,1993,SAO PAULO,2021-02-05,ÁSIA,SP
...,...,...,...,...,...,...,...,...
74705,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1977,SAO PAULO,2015-12-11,ÁFRICA,SP
74706,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1979,SAO PAULO,2015-12-11,ÁFRICA,SP
74707,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,BURKINA FASO,1986,SAO PAULO,2015-12-11,ÁFRICA,SP
74708,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,CUBA,1989,BRASILIA,2015-12-11,AMÉRICA,DF
74709,ERRO DE LANÇAMENTO NA LISTAGEM DA PLENÁRIA,2014,EGITO,1986,SAO PAULO,2015-12-11,ÁFRICA,SP

In [428]:
df_solicitacoes['CIDADE SOLICITAÇÃO'].unique()

array(['RIO DE JANEIRO', 'PORTO ALEGRE', 'SAO PAULO', 'PIRACICABA',
       'BRASILIA', 'SOROCABA', 'MANAUS', 'NITEROI', 'RECIFE',
       'CAXIAS DO SUL', 'CURITIBA', 'ITAJAI', 'BOA VISTA',
       'SAO JOSE DOS CAMPOS', 'MACEIO', 'ANGRA DOS REIS', 'GUARULHOS',
       'VARGINHA', 'BARRACAO', 'FORTALEZA', 'CAMPINAS', 'RIO BRANCO',
       'BAURU', 'SAO LUIS', 'CRICIUMA', 'PONTA GROSSA', 'PORTO VELHO',
       'JATAI', 'VITORIA', 'FOZ DO IGUACU', 'PACARAIMA', 'FLORIANOPOLIS',
       'GUARAPUAVA', 'ARACAJU', 'PONTA PORA', 'UBERLANDIA', 'JOAO PESSOA',
       'DIVINOPOLIS', 'NOVA IGUACU', 'CUIABA', 'ARARAQUARA', 'SANTAREM',
       'SINOP', 'BELO HORIZONTE', 'TABATINGA', 'URUGUAIANA',
       'SANTA MARIA', 'REDENCAO', 'ILHEUS', 'GOIANIA', 'IMPERATRIZ',
       'LONDRINA', 'SAO JOSE DO RIO PRETO', 'VOLTA REDONDA', 'BRASILEIA',
       'MARINGA', 'JAGUARAO', 'VILHENA', 'PORTO GRANDE',
       'CAMPOS DOS GOYTACAZES', 'GUAIRA', 'SALVADOR', 'CAMPO GRANDE',
       'NATAL', 'RONDONOPOLIS', 'SANTA VITORIA DO PALMAR', 'BAGE',
       'JOINVILLE', 'GUARUJA', 'TERESINA', '"A DEFINIR"', 'ITU',
       'JI-PARANA', 'CHAPECO', 'CASCAVEL', 'DOURADOS', 'GUAJARA',
       'RIBEIRAO PRETO', 'ARACATUBA', 'BELEM', 'ANAPOLIS', 'MINEIROS',
       'PRESIDENTE PRUDENTE', 'MACAE', 'JUIZ DE FORA', 'JUAZEIRO',
       'ERECHIM', 'GOVERNADOR VALADARES', 'LAGES', 'CRUZEIRO', 'ALTAMIRA',
       'MARABA', 'SANTA CRUZ DO SUL', 'MACAPA', 'EPITACIOLANDIA',
       'DIONISIO CERQUEIRA', 'CORUMBA', 'PORTO SEGURO', 'TRES LAGOAS',
       'OIAPOQUE', 'ARAGUAINA', 'UBERABA', 'CAMPINA GRANDE', 'ANANINDEUA',
       'DOIS VIZINHOS', 'NAVIRAI', 'CACERES', 'PALMAS', 'JALES', 'SANTOS',
       'PIRENOPOLIS', 'PASSO FUNDO', 'SANTO ANGELO', 'CABEDELO',
       'CARUARU', 'SAO SEBASTIAO', 'CRUZEIRO DO SUL',
       'VITORIA DA CONQUISTA', 'PELOTAS', 'SALGUEIRO', 'SAO MATEUS',
       'ITAI', 'PARNAIBA', 'RIO GRANDE', 'BARRA DO GARCAS',
       'SANTANA DO LIVRAMENTO', '0X2A', 'PARANAGUA'], dtype=object)